### ISSUE TITLE
Local compressed blob cache is broken on v2.1.y and nydusd panics

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/nydus#902]
When setting the compressed blob cache enabled, for the v6 image, the prefetch can't be started due to the absent blob meta.
Moreover, nydusd will panic.

```
[2022-11-29 14:33:15.109041 +08:00] INFO [api/src/http.rs:821] ---> Get Status Code: OK, Elapse: Ok(772.665µs), Body Size: 929
[2022-11-29 14:33:18.784357 +08:00] ERROR [/home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/log-panics-2.1.0/src/lib.rs:130] thread 'fuse_server' panicked at 'Chunk is not fully loaded': storage/src/device.rs:424
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/backtrace-0.3.66/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/log-panics-2.1.0/src/lib.rs:115:29
   2: std::panicking::rust_panic_with_hook
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:617:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   5: std::panicking::begin_panic
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:616:12
   6: nydus_storage::device::BlobIoChunk::as_base
             at data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:424:18
   7: <nydus_storage::device::BlobIoChunk as nydus_storage::device::BlobChunkInfo>::compressed_size
             at data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:473:9
   8: nydus_storage::device::BlobIoRange::new
             at data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:754:25
   9: <nydus_storage::cache::cachedfile::FileCacheEntry as nydus_storage::cache::BlobCache>::read
             at data00/home/gechangwei/git_repo/nydus-rs/storage/src/cache/cachedfile.rs:390:23
  10: <nydus_storage::device::BlobDeviceIoVec as fuse_backend_rs::common::file_traits::FileReadWriteVolatile>::read_vectored_at_volatile
             at data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:1147:24
  11: <&mut T as fuse_backend_rs::common::file_traits::FileReadWriteVolatile>::read_vectored_at_volatile
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/common/file_traits.rs:230:9
  12: fuse_backend_rs::transport::fusedev::FuseDevWriter<S>::write_from_at
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/transport/fusedev/mod.rs:216:19
  13: fuse_backend_rs::transport::Writer<S>::write_from_at
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/transport/mod.rs:537:35
  14: <fuse_backend_rs::api::server::ZcWriter<S> as fuse_backend_rs::api::filesystem::ZeroCopyWriter>::write_from
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/api/server/mod.rs:97:9
  15: nydus_storage::device::BlobDevice::read_to
             at data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:960:13
  16: <nydus_rafs::fs::Rafs as fuse_backend_rs::api::filesystem::sync_io::FileSystem>::read
             at data00/home/gechangwei/git_repo/nydus-rs/rafs/src/fs.rs:797:21
  17: fuse_backend_rs::api::vfs::sync_io::<impl fuse_backend_rs::api::filesystem::sync_io::FileSystem for fuse_backend_rs::api::vfs::Vfs>::read
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/api/vfs/sync_io.rs:333:17
  18: <alloc::sync::Arc<FS> as fuse_backend_rs::api::filesystem::sync_io::FileSystem>::read
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/api/filesystem/sync_io.rs:1044:9
  19: fuse_backend_rs::api::server::sync_io::<impl fuse_backend_rs::api::server::Server<F>>::read
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/api/server/sync_io.rs:354:15
  20: fuse_backend_rs::api::server::sync_io::<impl fuse_backend_rs::api::server::Server<F>>::handle_message
             at home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/fuse-backend-rs-0.9.6/src/api/server/sync_io.rs:67:46
  21: nydusd::fusedev::FuseServer::svc_loop
             at data00/home/gechangwei/git_repo/nydus-rs/src/bin/nydusd/fusedev.rs:121:21
  22: nydusd::fusedev::FusedevDaemon::kick_one_server::{{closure}}
             at data00/home/gechangwei/git_repo/nydus-rs/src/bin/nydusd/fusedev.rs:258:35
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  24: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:498:17
  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  26: std::panicking::try::do_call
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  27: __rust_try
  28: std::panicking::try
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  29: std::panic::catch_unwind
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  30: std::thread::Builder::spawn_unchecked_::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:497:30
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  33: start_thread
             at build/glibc-fWwxX8/glibc-2.28/nptl/pthread_create.c:486:8
  34: clone
             at build/glibc-fWwxX8/glibc-2.28/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by BraveY** [comment]
Need more information to reproduce this issue.
